name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  default:
    strategy:
      matrix:
        node:
          - 18.12.0
        os:
          - macos-latest
          - ubuntu-20.04
#          - windows-latest

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }}(Node.js ${{ matrix.node }})

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install libudev
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev

      - name: macos run
        if: matrix.os == 'macos-latest'
        run: | 
          npm i
          bash prepare.sh mac
          npm run test

      - name: ubuntu run
        if: matrix.os == 'ubuntu-20.04'
        run: |
          npm i
          bash prepare.sh linux
          npm run test

      - name: tar result
        if: always()
        run: |
          tar -zcvf tmp.${{ matrix.os  }}.tar.gz tmp
          rm -rf tmp

      - name: Publish reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: jfoa-build-reports-${{ runner.os }}
          path: tmp.${{ matrix.os  }}.tar.gz
